travis:
  secure:
    BINSTAR_TOKEN: bcN6MDFpIM4XknHamLC2NnT19s0+VwvRLj1L+d/6c1OzAcpPqlu/zjpvhUwzQz3i0/XjX81qYL/xHivvKVx8BTiBJlrb91QrI5y5DNK8XG4LQMaWVFuSG8NkKCsdokmodNtT/i0pNSzz7iQrFEh+5Ahl78ygP5cFHU9YOTr+zSPCpfhh3cevwsxldWuhB2wODIjZotybq8OvaKuCQdGzj5VbMwa7/WGZ6G0+J7ZkrQZAG7XmFDFGUhoylDz8Hu6IfwFCPmnhJPNlN4NH/wB+QvuIw0dbJVY/HTX7R1zj/i6j8D8LlB2O2JWKZTVMHT3gIB/eJgSD26zwnKbd6Kf9ZqHkIJEtj4J7V5Hksz74bQSAr1xxH+rh3ezAm2J8ZKCe2qU+nk0E7gjmNlQvoXLoQ20/qLy/9v7SQ63l8uQMaGQPxRF8jSLoPNjZS265h6uu5dkl3ivDEMTDA0wXxKOfoNRo7bC7CuAoFyO4QiUvUf0Vs06t5GJWNrjaPNGvD3M7Adt/3GWkkmb8/PLfdwkbQszbh4BB6GfRKWJ0xcMrQVSoyxWCzPJU4fx0/wk2eC9KGFF5cp8x5BdwINJog+sGgKKdsWmJDCTIhF8iAXQ7tcteUYpa/HwuwpO3kQXCK90KQKk7GPjUQn/aZzvCnCoFj4RUTa9gzvusKm4SXWeVERY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
